# Generated by Django 2.0.4 on 2018-05-30 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teacher_created_schools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='created_schools',
        ),
        migrations.AddField(
            model_name='school',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schools', to='core.Teacher'),
        ),
    ]
