# Generated by Django 2.0.4 on 2018-05-30 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teacher_lessons_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subjects', to='core.Teacher'),
        ),
    ]
