# Generated by Django 2.0.4 on 2018-05-30 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subject_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='lessons_templates',
        ),
        migrations.AddField(
            model_name='lessontemplate',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons_templates', to='core.Teacher'),
        ),
    ]
