# Generated by Django 2.0.4 on 2018-06-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180530_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
