# Generated by Django 2.0.4 on 2018-06-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_subject_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
