# Generated by Django 2.0.4 on 2018-06-03 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_group_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
